In [1]:
!wget textblob

--2023-12-03 16:17:05--  http://textblob/
Resolving textblob (textblob)... failed: Name or service not known.
wget: unable to resolve host address ‘textblob’

In [2]:
# Define the loss function and the optimizer
from textblob.classifiers import NaiveBayesClassifier
import nltk
nltk.download('punkt')

def naiveBayesclassifier(trainingset, testset):
    classifier = NaiveBayesClassifier(trainingset)
    for i in testset :
      print("document ", i, "           predicted class : ", classifier.classify(i[0]))
    print("Accuracy: ", classifier.accuracy(testset))

trainingset = [('London is the Capital of GB', 'GB'),
                ('Oxford is a city in GB', 'GB'), ('Dublin is the capital of Ireland', 'IE'), ('Limerick is a city in Ireland', 'IE')]
testset = [('University of Limerick', 'IE'),
('University College Dublin', 'IE'), ('Imperial college London', 'GB'), ('University of Oxford', 'GB'),
('Ireland & GB', 'GB')]

naiveBayesclassifier(trainingset, testset)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

document  ('University of Limerick', 'IE')            predicted class :  IE
document  ('University College Dublin', 'IE')            predicted class :  IE
document  ('Imperial college London', 'GB')            predicted class :  GB
document  ('University of Oxford', 'GB')            predicted class :  GB
document  ('Ireland & GB', 'GB')            predicted class :  IE
Accuracy:  0.8

In [4]:
!wget https://storage.googleapis.com/dataset-uploader/bbc/bbc-text.csv

--2023-12-03 16:19:13--  https://storage.googleapis.com/dataset-uploader/bbc/bbc-text.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.216.207, 173.194.217.207, 173.194.218.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.216.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5057493 (4.8M) [text/csv]
Saving to: ‘bbc-text.csv’

bbc-text.csv        100%[===================>]   4.82M  --.-KB/s    in 0.03s

2023-12-03 16:19:14 (150 MB/s) - ‘bbc-text.csv’ saved [5057493/5057493]

In [5]:
import pandas as pd
text_df = pd.read_csv('bbc-text.csv', header=None, delimiter = ',', names = ['category', 'text'])
text_df = text_df.drop(0)
display(text_df.head(100))

print("total number of documents :", len(text_df))
print ()
print("Document per category")
print(text_df['category'].value_counts())
print()


# splitting text_df 80/20
split_index = int(len(text_df) * 0.8)


train_df = text_df[:split_index]
test_df = text_df[split_index:]

print("train size",len(train_df))
print("test size",len(test_df))

print("Training set Samples")
print(train_df)
print("Test set Samples")
print(test_df)

          category                                               text
1             tech  tv future in the hands of viewers with home th...
2         business  worldcom boss  left books alone  former worldc...
3            sport  tigers wary of farrell  gamble  leicester say ...
4            sport  yeading face newcastle in fa cup premiership s...
5    entertainment  ocean s twelve raids box office ocean s twelve...
..             ...                                                ...
96           sport  dent continues adelaide progress american tayl...
97        business  oil rebounds from weather effect oil prices re...
98           sport  ireland win eclipses refereeing  errors  the i...
99        business  japan narrowly escapes recession japan s econo...
100  entertainment  rapper kanye west s shrewd soul us hip-hop sta...

[100 rows x 2 columns]

total number of documents : 2225

Document per category
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: category, dtype: int64

train size 1780
test size 445
Training set Samples
           category                                               text
1              tech  tv future in the hands of viewers with home th...
2          business  worldcom boss  left books alone  former worldc...
3             sport  tigers wary of farrell  gamble  leicester say ...
4             sport  yeading face newcastle in fa cup premiership s...
5     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
1776           tech  china  blocks google news site  china has been...
1777       politics  labour accused of  eu propaganda  a  taxpayer ...
1778          sport  tevez - an argentine in brazil some 65 years a...
1779       business  water firm suez in argentina row a conflict be...
1780  entertainment  tv presenter deeley drops cd:uk cat deeley has...

[1780 rows x 2 columns]
Test set Samples
           category                                               text
1781  entertainment  hobbit picture  four years away  lord of the r...
1782           tech  game firm holds  cast  auditions video game fi...
1783       politics  clarke plans migrant point scheme anyone plann...
1784          sport  radcliffe will compete in london paula radclif...
1785          sport  serena becomes world number two serena william...
...             ...                                                ...
2221       business  cars pull down us retail figures us retail sal...
2222       politics  kilroy unveils immigration policy ex-chatshow ...
2223  entertainment  rem announce new glasgow concert us band rem h...
2224       politics  how political squabbles snowball it s become c...
2225          sport  souness delight at euro progress boss graeme s...

[445 rows x 2 columns]

In [ ]:
import pandas as pd
text_df = pd.read_csv('bbc-text.csv', header=None, delimiter = ',', names = ['category', 'text'])
text_df = text_df.drop(0)
display(text_df.head(100))

print("total number of documents :", len(text_df))
print ()
print("Document per category")
print(text_df['category'].value_counts())
print()


# splitting text_df 80/20
split_index = int(len(text_df) * 0.8)


train_df = text_df[:split_index]
test_df = text_df[split_index:]

print("train size",len(train_df))
print("test size",len(test_df))

print("Training set Samples")
print(train_df)

print("Test set Samples")
print(test_df)


# changing the format ofthe text
text_list = train_df['text'].tolist()
category_list = train_df['category'].tolist()
train_tuples = list(zip(text_list, category_list))
# print for validation
print(train_tuples)
# calling the classifier
classifier = NaiveBayesClassifier(train_tuples)

k = []
for i in test_df['text'] :
    k.append(classifier.classify(i))
    # print(test_df['text'], k)
# adding the classified data to the test_tuples
test_list = test_df['text'].tolist()
test_tuples = list(zip(test_list, k))

# validation
print(test_tuples[:10])
# accuracy Printed
print("Accuracy :", classifier.accuracy(test_tuples))

          category                                               text
1             tech  tv future in the hands of viewers with home th...
2         business  worldcom boss  left books alone  former worldc...
3            sport  tigers wary of farrell  gamble  leicester say ...
4            sport  yeading face newcastle in fa cup premiership s...
5    entertainment  ocean s twelve raids box office ocean s twelve...
..             ...                                                ...
96           sport  dent continues adelaide progress american tayl...
97        business  oil rebounds from weather effect oil prices re...
98           sport  ireland win eclipses refereeing  errors  the i...
99        business  japan narrowly escapes recession japan s econo...
100  entertainment  rapper kanye west s shrewd soul us hip-hop sta...

[100 rows x 2 columns]

total number of documents : 2225

Document per category
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: category, dtype: int64

train size 1780
test size 445
Training set Samples
           category                                               text
1              tech  tv future in the hands of viewers with home th...
2          business  worldcom boss  left books alone  former worldc...
3             sport  tigers wary of farrell  gamble  leicester say ...
4             sport  yeading face newcastle in fa cup premiership s...
5     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
1776           tech  china  blocks google news site  china has been...
1777       politics  labour accused of  eu propaganda  a  taxpayer ...
1778          sport  tevez - an argentine in brazil some 65 years a...
1779       business  water firm suez in argentina row a conflict be...
1780  entertainment  tv presenter deeley drops cd:uk cat deeley has...

[1780 rows x 2 columns]

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

[('hobbit picture  four years away  lord of the rings director peter jackson has said that it will be up to four years before he starts work on a film version of the hobbit.  the oscar winner said on a visit to sydney there was a  desire  to make it  but not before lengthy negotiations.  i think it s gonna be a lot of lawyers sitting in a room trying to thrash out a deal before it will ever happen   said the new zealander. the rights to jrr tolkien s book are split between two major film studios. jackson  who is currently filming a remake of hollywood classic king kong  said he thought that the sale of mgm studios to the sony corporation would cast further uncertainty on the project. the 43-year-old was in the australian city to visit a lord of the rings exhibition  which has attracted 140 000 visitors since it opened in december.  the film-maker recently sued film company new line cinema for undisclosed damages over alleged withheld profits and lost revenue from the first part of the middle earth trilogy. the fellowship of the ring from 2001 went on to make worldwide profits of $291 million (£152 million). jackson is thought to have secured the most lucrative film directing deal in history to remake king kong  which is currently in production in wellington. the picture  which stars naomi watts and oscar winner adrien brody  is due to be released in december. jackson has also committed to making a film version of lovely bones  based on the best-selling book by alice sebold.', 'entertainment'), ('game firm holds  cast  auditions video game firm bioware is to hold open auditions for people to become cast members for future games.  the company  which makes role playing games such as knights of the old republic and neverwinter nights  is seeking people aged 18 to 99. the canada-based company says it was looking for  a wide variety of people to use as face models for characters . everyone chosen to appear in a video game will receive a performer s fee for the use of their image. the company is inviting people to come along to a shopping mall in west edmonton  alberta  on friday and saturday  bringing along a piece of photo identification.   there are hundreds and hundreds of characters in a typical bioware game   said shauna perry  bioware s audio and external resources producer.  those people live in any city and village and so we need ordinary people  people with interesting faces.  she added:  not everyone is a model in the world so we don t want just models in our games.  people chosen to appear in a game will have their head scanned in three dimensions. hundreds of photos of the person s head are taken so that a model of the head can be generated in 3d.  the 3d model will look exactly like the person - it s really quite incredible how detailed they are   said ms perry. she said chosen participants will have no control over how the image is used in a computer game.  we cannot give people any control over how the images are used.  but their face could be used in multiple games - so they could be the hero in one  the villain in another and just a merchant in a third.', 'tech'), ('clarke plans migrant point scheme anyone planning to move to the uk will have to pass a test to prove they can contribute to the country  home secretary charles clarke has said.  he is proposing a points system similar to australia s but would avoid the quota system planned by the tories. mr clarke  who will unveil his plans on monday  said economic migration helped the uk but  needed proper policing . the lib dems say they will look at his plans  but tory liam fox said his party offered a  clear choice  on the issue. the conservative party co-chairman said the british electorate had a choice between a labour government that had  done nothing for eight years and will not set a limit  on immigration and a tory one that would impose quotas.  the home secretary said  by 2008  he wanted everyone given a visa and entering the uk to have their fingerprints taken  to  ensure we can know everybody who is in the country . speaking on bbc one s breakfast with frost  he said  economic migrants are of great value to this country   but stressed that proper policing was needed to ensure that they do not become a  burden on society . he said:  we will establish a system ... which looks at the skills  talents and abilities of people seeking to come and work in this country  and ensures that when they come here they have a job and can contribute to the economy of the country.   the home secretary  whose five-year blueprint for immigration and asylum is expected to be published on monday  also rejected claims that the immigration debate encouraged bigotry.  the issue of who does come into this country  and whether they are entitled to be in this country  who does settle here  how we have border controls  is a perfectly legitimate aspect of public debate   he said. liberal democrat home affairs spokesman mark oaten said:  whilst it is good that labour has rejected the tory idea of quotas on asylum  the jury is still out on the home office s ability to deliver a fair and efficient asylum system.   mr howard has said britain should take its fair share of the world s  genuine refugees . but he claims the current asylum system is being abused - and with it britain s generosity. trevor phillips  chairman of the commission for racial equality  called on mr clarke to denounce the suggestion britain s hospitality was being tested by immigration.  tell that to the 44 000 doctors in the nhs and the 70 000 nurses without whom we would really see what pressure on the health service means   he said.  ditto the teachers  from south africa  australia  jamaica  who are reducing the sizes of our classes and schools.  the refugee council said mr howard s proposals would mean there would be no safe haven in the uk.', 'politics'), ('radcliffe will compete in london paula radcliffe will compete in the flora london marathon this year after deciding her schedule for 2005.  the 31-year-old won the race in 2002 on her marathon debut  defended her title 12 months later and will now seek a third title in the 17 april race.  it doesn t get any better than this for the 25th anniversary   said race director david bedford.  after announcing the greatest men s field ever we now have the greatest women s distance runner ever.  three years ago radcliffe smashed the women s world record in two hours 18 minutes 15 seconds.  the bedford star returned to london 12 months later  lowering her mixed-race world record of 2:17:18  which she set in chicago in october 2003  by one minute 53 secs. radcliffe s career took a setback when she failed to complete the olympic marathon and later dropped out of the athens 10 000m last august. but the 31-year-old bounced back to win the new york marathon in november. radcliffe  however  passed up the chance to go for the  big city  marathon grand slam. with wins in chicago  london and new york  only the boston marathon remains to be conquered but that takes place a day after london.  boston is definitely a race i want to do at some point  but london is very special to me   said radcliffe.  i don t pick races thinking about things like pressure. i pick the ones in my heart i really want to do.  i love the atmosphere  crowds and course and know it will always be a great quality race.  it is also the 25th anniversary this year which adds to the occasion.', 'sport'), ('serena becomes world number two serena williams has moved up five places to second in the world rankings after her australian open win.  williams won her first grand slam title since 2003 with victory over lindsay davenport  the world number one. men s champion marat safin remains fourth in the atp rankings while beaten finalist lleyton hewitt replaces andy roddick as world number two. roger federer retains top spot  but safin has overtaken hewitt to become the new leader of the champions race. alicia molik  who lost a three-set thriller against davenport in the quarter-finals  is in the women s top 10 for the first time in her career. her rise means australia have a player in the top 10 of the men s and women s rankings for the first time in 21 years. and britain s elena baltacha  who qualified and then reached the third round  has risen to 120 in the world - a leap of 65 places and her highest ranking yet.', 'sport'), ('ultimate game  award for doom 3 sci-fi shooter doom 3 has blasted away the competition at a major games ceremony  the golden joystick awards.  it was the only title to win twice  winning ultimate game of the year and best pc game at the awards  presented by little britain star matt lucas. the much-anticipated sci-fi horror doom 3 shot straight to the top of the uk games charts on its release in august. other winners included grand theft auto: san andreas which took the most wanted for christmas prize. only released last week  it was closely followed by halo 2 and half-life 2  which are expected to be big hits when they are unleashed later this month.  but they missed out on the prize for the most wanted game of 2005  which went to the nintendo title  the legend of zelda. the original doom  released in 1994  heralded a new era in computer games and introduced 3d graphics. it helped to establish the concept of the first-person shooter. doom 3 was developed over four years and is thought to have cost around $15m (£8.3m). the top honour for the best online game of the year went to battlefield vietnam. the chronicles of riddick: escape from butcher bay was handed the unsung hero game of 2004. its release was somewhat eclipsed by doom 3  which was released on the same week. it was  however  very well received by gamers and was praised for its storyline which differed from the film released around the same time. electronic arts was named top publisher of the year  taking the crown from nintendo which won in 2003. the annual awards are voted for by more than 200 000 readers of computer and video games magazines. games awards like this have grown in importance. over the last six years  the uk market for games grew by 100% and was worth a record £1 152m in 2003  according to a recent report by analysts screen digest.', 'tech'), ('algeria hit by further gas riots algeria suffered a weekend of violent protests against government plans to raise gas prices  local press reports.  demonstrators in a number of regions blocked roads  attacked public buildings and overturned vehicles  newspapers including el watan reported. the price of butane gas  a vital fuel for cooking  has risen to 200 dinars ($2.77) per canister from 170 dinars. even before the hike  failing economic conditions had been fanning resentment in some of algeria s poorest regions.  demonstrators took to the streets last week when the cost change was first announced  but police seemed to have restored order. according to local press reports  trouble flared up again on saturday and carried on into sunday. el watan said that a number of hot spots centred on the villages and towns close to bouira  about 100 kilometres (60 miles) south of the capital algiers. among the other main areas affected were the western tiaret region and sidi ammar in the east of the country  agence france presse (afp) reported. riots also flared up in the maghnia region close to the border with morocco in the west  afp said. butane gas and fuel oil are used as the main source of fuel to heat homes and cook food in algeria s remote mountain areas.', 'business'), ('fast lifts rise into record books two high-speed lifts at the world s tallest building have been officially recognised as the planet s fastest.  the lifts take only 30 seconds to whisk passengers to the top of the 508m tall tfc 101 tower in taipei  taiwan. the guinness book of records has declared the 17m per second speed of the two lifts the swiftest on earth. the lifts also have a pressure control system to stop passengers  ears popping as they ascend and descend at high speed.  in total  the tfc tower has 61 lifts  34 of them double-deckers  and 50 escalators to shuttle people around its 106 floors. the tfc 101 tower is due to be officially opened on 31 december.  the super-fast lifts can speed up to 24 passengers to the tip of the tower in about 30 seconds  while ascending their 382m track. the 17m/s top speed of the lifts translates to about 38mph (61km/h). curiously the lifts take longer to descend and spend almost a whole minute returning to ground level from the top of the tfc tower. the key new technologies applied in the world s fastest elevators include:    - a pressure control system  which adjusts the atmospheric pressure inside a car by using suction and discharge blowers  preventing  ear popping    - an active control system which tries to balance the lift more finely and remove the sources of vibrations   - streamlined cars to reduce the whistling noise produced by running the lifts at a high speed inside a narrow shaft      the certification of our elevators as world record-holders by the authoritative guinness world records is a great honour for us   said masayuki shimono  president of manufacturer toshiba elevator and building systems which installed the lifts. the first record for the world s fastest passenger elevators was published in the first edition of the guinness book of records in 1955.  as such  it is an interesting indicator of how technology has advanced in the 50 years since that first edition  when the record was 426m per minute  or 25.6 km/h  less than half the speed of the new record   said hein le roux  specialist researcher at the guinness world records. taipei s tfc 101 tower is more than 50m taller than the petronas towers in kuala lumpur  malaysia - formerly the world s tallest skyscraper.', 'tech'), ('muslim group attacks tv drama 24 a british muslim group has criticised the new series of us drama 24  which is about to be aired on sky one  claiming it portrays islam unfairly.  the muslim council of britain has complained to broadcasting watchdog ofcom. it says the programme breaches editorial guidelines. the group s members met with sky executives on tuesday after viewing previews of the first five episodes. the drama  now in its fourth series  begins on sunday evening. the new series portrays a muslim family as a sleeper terrorist cell. the muslim council of britain said in a statement:  we are greatly concerned by the unremittingly hostile and unbalanced portrayal of muslims in this series of 24 based upon a preview of the first five episodes that we have seen.   there is not a single positive muslim character in the storyline to date. at a time when negative stereotypes of muslims are on the increase we feel that sky - as a major uk broadcaster - has a responsibility to challenge these insidious views  not help to reinforce them.  but sky denied the programme breached broadcasting guidelines. a spokesperson said:  during a useful meeting yesterday  sky listened to the concerns raised by representatives of the council. sky does not believe that the episodes that it has reviewed to date breach ofcom s programme code.  fox tv  which shows the series in the us  is broadcasting public service announcements showing muslims in a positive light after complaints about the series.', 'entertainment'), ('us tv special for tsunami relief a us television network will screen a celebrity tv special to benefit the tsunami relief effort in south asia.  nbc will encourage viewer donations during an hour-long show featuring musical performances on 15 january. actress sandra bullock has donated $1m (£525 000) to the american red cross and actor leonardo dicaprio pledged a  sizable  aid contribution to unicef. meanwhile 70 hong kong music and movie stars re-recorded we are the world in mandarin and cantonese to raise funds.  the song will not be released as a single  but will be played regularly during a chinese telethon on friday in aid of victims of the boxing day disaster. around 140 000 people were killed and five million left homeless or without food and water after an earthquake below the indian ocean sent waves crashing into coastal communities in 11 countries.  the united nations warned that the number killed in the disaster could rise sharply  with aid yet to reach some remote areas. performers have yet to be confirmed for nbc s aid relief benefit later this month. it follows a two-hour telethon carried by all four major us television networks 10 days after the 11 september terror attacks in 2001. america: a tribute to heroes raised more than $150m (£79m) to help victims of the suicide attacks on the world trade center and pentagon.', 'entertainment')]
Accuracy : 1.0